Boa noite ana aqui é  Iatamar esse é o script do banco de dados 


CREATE TABLE [dbo].[EMPRESA] (
    [IDEMPRESA]   UNIQUEIDENTIFIER NOT NULL,
    [RAZAOSOCIAL] NVARCHAR (150)   NOT NULL,
    [CNPJ]        NVARCHAR (25)    NOT NULL,
    PRIMARY KEY CLUSTERED ([IDEMPRESA] ASC),
    UNIQUE NONCLUSTERED ([CNPJ] ASC)
);

CREATE TABLE [dbo].[FUNCIONARIO] (
    [IDFUNCIONARIO] UNIQUEIDENTIFIER NOT NULL,
    [NOME]          NVARCHAR (150)   NOT NULL,
    [CPF]           NVARCHAR (15)    NOT NULL,
    [MATRICULA]     NVARCHAR (15)    NOT NULL,
    [DATAADMISSAO]  DATE             NOT NULL,
    [IDEMPRESA]     UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY CLUSTERED ([IDFUNCIONARIO] ASC),
    UNIQUE NONCLUSTERED ([CPF] ASC),
    UNIQUE NONCLUSTERED ([MATRICULA] ASC),
    FOREIGN KEY ([IDEMPRESA]) REFERENCES [dbo].[EMPRESA] ([IDEMPRESA])
);

//////////////// rodar esse por ultimo serve pra pegar as informações em um select só entre tabela empresa e funcionario ////////////////////
CREATE VIEW VW_FUNCIONARIOS
AS 
SELECT 
	F.IDFUNCIONARIO,
	F.NOME,
	F.CPF,
	F.MATRICULA,
	F.DATAADMISSAO,
	E.RAZAOSOCIAL,
	E.CNPJ
FROM FUNCIONARIO F
INNER JOIN EMPRESA E
ON F.IDEMPRESA = E.IDEMPRESA